/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author jhonw
 */
public class GUIPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIPrincipal.class.getName());

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSelección = new javax.swing.JLabel();
        comboColor = new javax.swing.JComboBox<>();
        btnHistoria = new javax.swing.JButton();
        btnInstrucciones = new javax.swing.JButton();
        btnCreditos = new javax.swing.JButton();
        btnJugar = new javax.swing.JButton();
        imgFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio demo");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSelección.setBackground(new java.awt.Color(0, 51, 102));
        lblSelección.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblSelección.setForeground(new java.awt.Color(255, 255, 255));
        lblSelección.setText("Selección de color");
        getContentPane().add(lblSelección, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 210, -1));

        comboColor.setBackground(new java.awt.Color(0, 51, 102));
        comboColor.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        comboColor.setForeground(new java.awt.Color(255, 255, 255));
        comboColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Azul", "Verde", "Rojo", "Amarillo" }));
        getContentPane().add(comboColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        btnHistoria.setBackground(new java.awt.Color(0, 51, 102));
        btnHistoria.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnHistoria.setForeground(new java.awt.Color(255, 255, 255));
        btnHistoria.setText("Historia");
        btnHistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoriaActionPerformed(evt);
            }
        });
        getContentPane().add(btnHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, -1, -1));

        btnInstrucciones.setBackground(new java.awt.Color(0, 51, 102));
        btnInstrucciones.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnInstrucciones.setForeground(new java.awt.Color(255, 255, 255));
        btnInstrucciones.setText("Instrucciones");
        btnInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstruccionesActionPerformed(evt);
            }
        });
        getContentPane().add(btnInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, -1, -1));

        btnCreditos.setBackground(new java.awt.Color(0, 51, 102));
        btnCreditos.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnCreditos.setForeground(new java.awt.Color(255, 255, 255));
        btnCreditos.setText("Créditos");
        btnCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditosActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        btnJugar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton.png"))); // NOI18N
        btnJugar.setContentAreaFilled(false);
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });
        getContentPane().add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 230, 90));

        imgFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imgInicio_1.png"))); // NOI18N
        getContentPane().add(imgFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstruccionesActionPerformed
    GUIInstrucciones instru = new GUIInstrucciones();
    instru.setVisible(true);
    instru.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnInstruccionesActionPerformed

    private void btnCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditosActionPerformed
    GUICreditos credi = new GUICreditos();
    credi.setVisible(true);
    credi.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnCreditosActionPerformed

    private void btnHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoriaActionPerformed
    GUIHistoria histo = new GUIHistoria();
    histo.setVisible(true);
    histo.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnHistoriaActionPerformed

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
    GUIJuego juego = new GUIJuego();
    juego.setVisible(true);
    juego.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnJugarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreditos;
    private javax.swing.JButton btnHistoria;
    private javax.swing.JButton btnInstrucciones;
    private javax.swing.JButton btnJugar;
    private javax.swing.JComboBox<String> comboColor;
    private javax.swing.JLabel imgFondo;
    private javax.swing.JLabel lblSelección;
    // End of variables declaration//GEN-END:variables
}
