/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.Dado;
import Model.Preguntas;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author jhonw
 */
public class PanelControl extends javax.swing.JPanel {

    /**
     * Creates new form PanelTablero
     */
    public PanelControl() {
        initComponents();
    }

    public JButton getBtnDado() {
        return btnDado;
    }

    public JButton getBtnReinicio() {
        return btnReinicio;
    }
    
    //se modifica el set para recibir el valor del dado
    public void setNumeroDado(int valor)
    {
        lblNumeroDado.setText("Numero dado: " + valor);
    }
    
    //
    public void setTextoTurno(String texto)
    {
        lblFichaTurno.setText("Ficha turno: " + texto);
    }

    public JLabel getTxtTiempo()
    {
        return txtTiempo;
    }

    public void setTxtTiempo(int segundos) 
    {
        txtTiempo.setText("Tiempo:" + segundos);
    }

    public JLabel getTxtPuntosJugador()
    {
        return txtPuntosJugador;
    }

    public void setTxtPuntosJugador(int puntosJugador) 
    {
        txtPuntosJugador.setText("Puntos jugador: " + puntosJugador);
    }

    public JLabel getTxtPuntosOponentes() 
    {
        return txtPuntosOponentes;
    }

    public void setTxtPuntosOponentes(int puntosOponente) 
    {
        txtPuntosOponentes.setText("Puntos Oponente: " + puntosOponente);
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDado = new javax.swing.JButton();
        btnReinicio = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblNumeroDado = new javax.swing.JLabel();
        lblFichaTurno = new javax.swing.JLabel();
        txtTiempo = new javax.swing.JLabel();
        txtPuntosJugador = new javax.swing.JLabel();
        txtPuntosOponentes = new javax.swing.JLabel();

        btnDado.setText("Dado");
        btnDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDadoActionPerformed(evt);
            }
        });

        btnReinicio.setText("Reinicio");

        jButton3.setText("Menú");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lblNumeroDado.setText("Número dado");

        lblFichaTurno.setText("Ficha turno");

        txtTiempo.setText("Tiempo");

        txtPuntosJugador.setText("Puntos Jugador:");

        txtPuntosOponentes.setText("Puntos Oponentes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDado)
                    .addComponent(lblNumeroDado)
                    .addComponent(lblFichaTurno)
                    .addComponent(txtPuntosOponentes)
                    .addComponent(jButton3)
                    .addComponent(txtTiempo)
                    .addComponent(txtPuntosJugador)
                    .addComponent(btnReinicio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnDado)
                .addGap(18, 18, 18)
                .addComponent(lblNumeroDado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFichaTurno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTiempo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPuntosJugador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPuntosOponentes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReinicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadoActionPerformed
    Dado dadito = new Dado();
    Preguntas preguntita = new Preguntas();
    }//GEN-LAST:event_btnDadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDado;
    private javax.swing.JButton btnReinicio;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel lblFichaTurno;
    private javax.swing.JLabel lblNumeroDado;
    private javax.swing.JLabel txtPuntosJugador;
    private javax.swing.JLabel txtPuntosOponentes;
    private javax.swing.JLabel txtTiempo;
    // End of variables declaration//GEN-END:variables
}
