/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
/**
 *
 * @author jhonw
 */
public class PanelTablero extends javax.swing.JPanel 
{

    /**
     * Creates new form PanelTablero
     */
    //constructor
    public PanelTablero() 
    {
        initComponents();
        this.addMouseListener(new MouseAdapter()
        {
            @Override
            public void mousePressed(MouseEvent e)
                {
                    Point p = e.getPoint();
                    moverFicha(p);
                }
            
        });
    }// fin del constructor
    
    public void moverFicha(Point p)
    {
        //clase point
        imgFichaRoja.setLocation(p);
        System.out.println("Coordenadas: " + p.x + " , " + p.y);
    }//fin del metodo mover ficha
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgFichaRoja = new javax.swing.JLabel();
        imgTablero = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgFichaRoja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FichaRoja.png"))); // NOI18N
        add(imgFichaRoja, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 20, 40));

        imgTablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tablerografico.png"))); // NOI18N
        add(imgTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgFichaRoja;
    private javax.swing.JLabel imgTablero;
    // End of variables declaration//GEN-END:variables
}
